---
# Does an "apt-get update" on remote
#

- hosts: mine
  tasks: 
  - name: Update the cache
    apt: 
      update_cache: yes
    become: yes

  - name: List packages to upgrade (1/2)
    command: aptitude -q -F%p --disable-columns search "~U"
    register: updates

  - name: List packages to upgrade (2/2)
    debug: msg="{{ updates.stdout_lines | count }} packages to upgrade ({{ updates.stdout_lines | join(', ') }})"

  - name: Upgrade all packages to the latest version
    apt:
      upgrade: safe
    become: yes
