---
# Try to determine the IP-adresses and HW-adresses from remote hosts.
#

- hosts: all
  tasks: 
  - name: Check IP Adresses
    command: ip addr  
    register: my_ip_addr

  - debug: msg="{{ my_ip_addr.stdout }}"

#  shell: host {{ ansible_fqdn }} | awk '{print $NF}' ; test ${PIPESTATUS[0]} -eq 0 
